version: '3.7'
services:
  server:
    container_name: edwrd-server
    build:
      context: ./server
    command: /app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 5000:5000
    restart: always
    env_file: .env
  client:
    container_name: edwrd-client
    build:
      context: ./client
    command: yarn start
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: always
    ports:
      - 3000:3000
  mongo:
    container_name: edwrd-db
    image: mongo
    volumes:
      - ${EDWRD_DB_DATA}:/data/db
    ports:
      - 27017:27017
