version: '3.7'
services:
  web:
    container_name: edwrd-web-dev
    build: .
    volumes:
      - ${EDWRD_LOGS_DIR}:/app/server/src/logs
    ports:
      - 5000:5000
    restart: always
    env_file: ./.env
  mongo:
    container_name: edwrd-db
    image: mongo
    volumes:
      - ${EDWRD_DB_DATA}:/data/db
    ports:
      - 27017:27017
