const rules = require('./rules');

const formSchema = {
  cropSelection: rules.string,
  darea: rules.number,
  dareaIncSurfaceRunoff: rules.boolean,
  devDateEnd: rules.string,
  devDateStart: rules.string,
  harvestDateStart: rules.string,
  iarea: rules.number,
  initCropHeight: rules.number,
  initDateEnd: rules.string,
  initDateStart: rules.string,
  initKC: rules.number,
  irrdep: rules.string,
  irrdepType: rules.string,
  lateDateEnd: rules.string,
  lateDateStart: rules.string,
  midCropHeight: rules.number,
  midDateEnd: rules.string,
  midDateStart: rules.string,
  midKC: rules.number,
  pfact: rules.number,
  plantDateStart: rules.string,
  rarea: rules.number,
  rdep: rules.number,
  rew: rules.number,
  rseep: rules.number,
  soilDateEnd: rules.string,
  soilDateStart: rules.string,
  soilType: rules.string,
  unitType: rules.string,
  userData: rules.boolean,
  ze: rules.number,
  zefc: rules.number,
  zewp: rules.number,
  zr: rules.number,
  zrfc: rules.number,
  zrwp: rules.number,
};

module.exports.formSchema = formSchema;
