const rules = require('./rules');

const formSchema = {
  cropSelection: rules.string,
  darea: rules.float,
  dareaIncSurfaceRunoff: rules.boolean,
  devDateEnd: rules.string,
  devDateStart: rules.string,
  harvestDateStart: rules.string,
  iarea: rules.float,
  initCropHeight: rules.float,
  initDateEnd: rules.string,
  initDateStart: rules.string,
  initKC: rules.float,
  irrdep: rules.string,
  irrdepType: rules.string,
  lateDateEnd: rules.string,
  lateDateStart: rules.string,
  midCropHeight: rules.float,
  midDateEnd: rules.string,
  midDateStart: rules.string,
  midKC: rules.float,
  pfact: rules.float,
  plantDateStart: rules.string,
  rarea: rules.float,
  rdep: rules.float,
  rew: rules.float,
  rseep: rules.float,
  soilDateEnd: rules.string,
  soilDateStart: rules.string,
  soilType: rules.string,
  unitType: rules.string,
  userData: rules.boolean,
  ze: rules.float,
  zefc: rules.float,
  zewp: rules.float,
  zr: rules.float,
  zrfc: rules.float,
  zrwp: rules.float,
};

module.exports.formSchema = formSchema;
